INSERT INTO CO2_LEVELS (CITY, DISTRICT, CO2READING_VALUE, READING_TS) VALUES
    ('WIEN', 'Penzing' , 20.5, CURRENT_TIMESTAMP());
INSERT INTO CO2_LEVELS (CITY, DISTRICT, CO2READING_VALUE, READING_TS) VALUES
    ('WIEN', 'Penzing' , 20.45, TIMESTAMPADD(MINUTE, 5, CURRENT_TIMESTAMP()));
INSERT INTO CO2_LEVELS (CITY, DISTRICT, CO2READING_VALUE, READING_TS) VALUES
    ('WIEN', 'Penzing' , 20.45, TIMESTAMPADD(DAY, -40, CURRENT_TIMESTAMP()));

INSERT INTO CO2_LEVELS (CITY, DISTRICT, CO2READING_VALUE, READING_TS) VALUES
    ('WIEN', 'Währing' , 21.5, CURRENT_TIMESTAMP());
INSERT INTO CO2_LEVELS (CITY, DISTRICT, CO2READING_VALUE, READING_TS) VALUES
    ('WIEN', 'Währing' , 21.45, TIMESTAMPADD(MINUTE, 5, CURRENT_TIMESTAMP()));
INSERT INTO CO2_LEVELS (CITY, DISTRICT, CO2READING_VALUE, READING_TS) VALUES
    ('WIEN', 'Währing' , 21.45, TIMESTAMPADD(DAY, -40, CURRENT_TIMESTAMP()));

INSERT INTO CO2_LEVELS (CITY, DISTRICT, CO2READING_VALUE, READING_TS) VALUES
    ('BARCELONA', 'Gràcia' , 25.5, CURRENT_TIMESTAMP());
INSERT INTO CO2_LEVELS (CITY, DISTRICT, CO2READING_VALUE, READING_TS) VALUES
    ('BARCELONA', 'Gràcia' , 25.45, TIMESTAMPADD(MINUTE, 5, CURRENT_TIMESTAMP()));
INSERT INTO CO2_LEVELS (CITY, DISTRICT, CO2READING_VALUE, READING_TS) VALUES
    ('BARCELONA', 'Gràcia' , 25.45, TIMESTAMPADD(DAY, -40, CURRENT_TIMESTAMP()));

INSERT INTO CO2_LEVELS (CITY, DISTRICT, CO2READING_VALUE, READING_TS) VALUES
    ('BARCELONA', 'Eixample' , 22.5, CURRENT_TIMESTAMP());
INSERT INTO CO2_LEVELS (CITY, DISTRICT, CO2READING_VALUE, READING_TS) VALUES
    ('BARCELONA', 'Eixample' , 22.45, TIMESTAMPADD(MINUTE, 5, CURRENT_TIMESTAMP()));
INSERT INTO CO2_LEVELS (CITY, DISTRICT, CO2READING_VALUE, READING_TS) VALUES
    ('BARCELONA', 'Eixample' , 22.45, TIMESTAMPADD(DAY, -40, CURRENT_TIMESTAMP()));

INSERT INTO CO2_LEVELS (CITY, DISTRICT, CO2READING_VALUE, READING_TS) VALUES
    ('MÜNCHEN', 'Eixample' , 19.5, CURRENT_TIMESTAMP());
INSERT INTO CO2_LEVELS (CITY, DISTRICT, CO2READING_VALUE, READING_TS) VALUES
    ('MÜNCHEN', 'Eixample' , 19.45, TIMESTAMPADD(MINUTE, 5, CURRENT_TIMESTAMP()));
INSERT INTO CO2_LEVELS (CITY, DISTRICT, CO2READING_VALUE, READING_TS) VALUES
    ('MÜNCHEN:', 'Eixample' , 19.45, TIMESTAMPADD(DAY, -40, CURRENT_TIMESTAMP()));